name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t my-test .

    - name: Run container
      run: docker run my-test